# -*- coding: utf-8 -*-
"""TPS_Analysis_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0vP4tcGt87JSs3bCFv9WrfshJqcmVPU
"""

import os, zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from collections import defaultdict, deque

import statsmodels.formula.api as smf

EVENTS_XLSX = "./datasets/Event_Dataset.xlsx"

def _clean_cols(df):
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df

def _find_col(cols, candidates):
    for c in candidates:
        if c in cols:
            return c
    return None

def load_events_standardized(xlsx_path: str) -> pd.DataFrame:
    xls = pd.ExcelFile(xlsx_path)
    all_events = []

    for sheet in xls.sheet_names:
        df = pd.read_excel(xlsx_path, sheet_name=sheet)
        df = _clean_cols(df)

        cols = df.columns.tolist()

        # --- date column varies by sheet label ---
        date_col = _find_col(cols, ["Date (YYYY-MM-DD)", "Date (DD-MM-YYYY)", "Date"])
        if date_col is None:
            continue

        # --- start time ---
        start_col = _find_col(cols, ["StartTime", "Start Time", "starttime"])
        if start_col is None:
            continue

        # --- name + category (some sheets have weird casing like EventNAMe) ---
        name_col = _find_col(cols, ["EventName", "EventNAMe", "Event Name"])
        cat_col  = _find_col(cols, ["Category", "EventCategory", "Event Category"])

        # --- coordinates (BUT: they are swapped in your file) ---
        # In your sheets, "Longitude/Longtitude" actually stores LAT (~43.xx)
        # and "Latitude" actually stores LON (~-79.xx)
        lon_like = _find_col(cols, ["Longitude", "Longtitude"])
        lat_like = _find_col(cols, ["Latitude"])

        # Exhibition Place sheet has no lat/lon columns -> skip (or add manually later)
        if lon_like is None or lat_like is None:
            continue

        tmp = pd.DataFrame({
            "venue": sheet,
            "event_name": df[name_col] if name_col else None,
            "event_category": df[cat_col] if cat_col else None,
            "event_date_raw": df[date_col],
            "event_start_time_raw": df[start_col],
            # FIX SWAP:
            "venue_lat": pd.to_numeric(df[lon_like], errors="coerce"),
            "venue_lon": pd.to_numeric(df[lat_like], errors="coerce"),
        })

        # Parse date
        tmp["event_date"] = pd.to_datetime(tmp["event_date_raw"], errors="coerce").dt.date

        # Parse time (handles "19:00" and "10:00:00")
        tmp["event_start_time"] = pd.to_datetime(
            tmp["event_start_time_raw"].astype(str),
            errors="coerce"
        ).dt.time

        # Combine to start_dt
        tmp["start_dt"] = pd.to_datetime(
            tmp["event_date"].astype(str) + " " + tmp["event_start_time"].astype(str),
            errors="coerce"
        )

        tmp = tmp.drop(columns=["event_date_raw", "event_start_time_raw"])

        # Clean missing names/categories
        tmp["event_name"] = tmp["event_name"].fillna("UnknownEvent")
        tmp["event_category"] = tmp["event_category"].fillna("UnknownCategory")

        # Drop invalid rows
        tmp = tmp.dropna(subset=["start_dt", "venue_lat", "venue_lon"]).copy()

        all_events.append(tmp)

    events = pd.concat(all_events, ignore_index=True) if all_events else pd.DataFrame()

    # Filter to 2014–2025 inclusive
    events = events[(events["start_dt"].dt.year >= 2014) & (events["start_dt"].dt.year <= 2025)].copy()

    # Deduplicate (same venue + same start_dt + same category + same name)
    events = events.drop_duplicates(subset=["venue", "start_dt", "event_category", "event_name"]).reset_index(drop=True)

    return events

events = load_events_standardized(EVENTS_XLSX)

print(events.shape)
display(events.head(10))

# ---------- Time range ----------
MIN_YEAR, MAX_YEAR = 2017, 2025

# ---------- Crime → TTC mapping ----------
CRIME_TO_STOP_MAX_M = 300     # assign crime to stop/hub if within this distance (m)

# ---------- Venue nearby-hub selection ----------
VENUE_RADIUS_M = 500         # hubs within this radius are considered "venue access" candidates

# ---------- Event window (start-based, robust to unknown end times) ----------
PRE_HOURS  = 1
POST_HOURS =5
PANEL_FREQ = "h"

# ---------- Propagation settings ----------
# We will make hop thresholds mode-aware using a TARGET network distance and median edge length
TARGET_DIST_M = 3000

# Control ring in hop space (farther hops)
CONTROL_HOPS_MIN = 6
CONTROL_HOPS_MAX = 12

"""### Utility helpers"""

def clean_cols(df):
    df = df.copy()
    df.columns = [str(c).strip().lower().replace("\n"," ").replace("  "," ") for c in df.columns]
    return df

def haversine_m(lat1, lon1, lat2, lon2):
    R = 6371000.0
    lat1 = np.radians(lat1); lon1 = np.radians(lon1)
    lat2 = np.radians(lat2); lon2 = np.radians(lon2)
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin(dlon/2)**2
    c = 2*np.arcsin(np.sqrt(a))
    return R*c

def toronto_like_latlon(lat_s, lon_s):
    """
    Heuristic: Toronto area ~ lat 43-44, lon -80 to -78
    Returns True if medians look correct.
    """
    lat_med = np.nanmedian(lat_s)
    lon_med = np.nanmedian(lon_s)
    return (43.0 <= lat_med <= 44.5) and (-80.5 <= lon_med <= -78.0)

def autoswap_latlon(df, lat_col, lon_col, out_lat="lat", out_lon="lon"):
    """
    Creates numeric out_lat/out_lon from df[lat_col]/df[lon_col].
    Auto-swaps if they don't look like Toronto but swapped does.
    """
    lat = pd.to_numeric(df[lat_col], errors="coerce")
    lon = pd.to_numeric(df[lon_col], errors="coerce")
    if toronto_like_latlon(lat, lon):
        df[out_lat] = lat
        df[out_lon] = lon
        df["_latlon_swapped"] = False
        return df
    # try swap
    if toronto_like_latlon(lon, lat):
        df[out_lat] = lon
        df[out_lon] = lat
        df["_latlon_swapped"] = True
        return df
    # neither looks right; keep original
    df[out_lat] = lat
    df[out_lon] = lon
    df["_latlon_swapped"] = None
    return df

"""# PART 1 — Load TTC GTFS (stops, routes, trips, stop_times)"""

stops = pd.read_csv("./datasets/TTC Routes and Schedules Data/stops.txt")
stop_times = pd.read_csv("./datasets/TTC Routes and Schedules Data/stop_times.txt")
trips = pd.read_csv("./datasets/TTC Routes and Schedules Data/trips.txt")
routes = pd.read_csv("./datasets/TTC Routes and Schedules Data/routes.txt")
crime_raw = pd.read_csv("datasets/Major_Crime_Indicators_Open_Data.csv")

crime_raw = crime_raw.drop_duplicates(subset=crime_raw.columns.difference(['OBJECTID']))

crime_raw.shape

# Keep essential columns (if present)
stops_cols = [c for c in ["stop_id","stop_name","stop_lat","stop_lon","location_type","parent_station"] if c in stops.columns]
stops = stops[stops_cols].copy()

stops["stop_id"] = stops["stop_id"].astype(str)
stops["stop_lat"] = pd.to_numeric(stops["stop_lat"], errors="coerce")
stops["stop_lon"] = pd.to_numeric(stops["stop_lon"], errors="coerce")
stops = stops.dropna(subset=["stop_lat","stop_lon"]).reset_index(drop=True)

# Ensure ids are strings
routes["route_id"] = routes["route_id"].astype(str)
trips["trip_id"] = trips["trip_id"].astype(str)
trips["route_id"] = trips["route_id"].astype(str)
stop_times["trip_id"] = stop_times["trip_id"].astype(str)
stop_times["stop_id"] = stop_times["stop_id"].astype(str)

stops.head(), stops.shape

"""# PART 2 — Build stop↔routes/modes + collapse platforms into hubs

## stop_id → routes served (join stop_times → trips → routes)
**This attaches “which lines serve this stop” and “what mode is this stop”**
"""

# stop_id -> trip_id
stop_trip = stop_times[["trip_id","stop_id"]].drop_duplicates()

# trip_id -> route_id
trip_route = trips[["trip_id","route_id"]].drop_duplicates()

# route metadata (short name + type)
route_meta_cols = [c for c in ["route_id","route_short_name","route_long_name","route_type"] if c in routes.columns]
route_meta = routes[route_meta_cols].drop_duplicates()

sr = stop_trip.merge(trip_route, on="trip_id", how="left").dropna(subset=["route_id"])
sr = sr.merge(route_meta, on="route_id", how="left")

# Aggregate to stop
stop_routes = (
    sr.groupby("stop_id")
      .agg(
          route_ids=("route_id", lambda x: sorted(set(x))),
          route_short_names=("route_short_name", lambda x: sorted(set(map(str, x.dropna())))),
          route_types=("route_type", lambda x: sorted(set(pd.to_numeric(x, errors="coerce").dropna().astype(int))))
      )
      .reset_index()
)

stop_routes.head()

# stops = pd.read_csv("./datasets/TTC Routes and Schedules Data/stops.txt")

stops

"""## STOP MODE TABLE
**Uses stop_routes built from stop_times→trips→routes join**
**Creates a stop-level table with a mode label so you can pick nearest bus/subway/streetcar stops near a venue**
"""

# stops2 = stops + route info
stops2 = stops.copy()
stops2["stop_id"] = stops2["stop_id"].astype(str)
stops2["stop_lat"] = pd.to_numeric(stops2["stop_lat"], errors="coerce")
stops2["stop_lon"] = pd.to_numeric(stops2["stop_lon"], errors="coerce")
stops2 = stops2.dropna(subset=["stop_lat","stop_lon"]).copy()

# attach routes per stop (stop_routes must already exist)
stops2 = stops2.merge(stop_routes, on="stop_id", how="left")

def stop_mode(route_types):
    """Primary mode for a stop."""
    if not isinstance(route_types, list):
        return "unknown"
    if 1 in route_types: return "subway"
    if 0 in route_types: return "streetcar"
    if 3 in route_types: return "bus"
    return "other"

stops2["mode"] = stops2["route_types"].apply(stop_mode)

# quick check
stops2["mode"].value_counts(dropna=False)

stops2

"""# PART 5 — Build TTC network + mode-aware hop thresholds

## Build adjacency edges (stop-level) from stop_times
**Hop propagation requires a graph. This uses actual GTFS trip order.**
"""

st = stop_times[["trip_id","stop_id","stop_sequence"]].copy()
st["stop_sequence"] = pd.to_numeric(st["stop_sequence"], errors="coerce")
st = st.dropna(subset=["stop_sequence"]).sort_values(["trip_id","stop_sequence"])
st["next_stop_id"] = st.groupby("trip_id")["stop_id"].shift(-1)

edges = st.dropna(subset=["next_stop_id"])[["trip_id","stop_id","next_stop_id"]].drop_duplicates()
edges.rename(columns={"stop_id":"u","next_stop_id":"v"}, inplace=True)

# undirected
edges_undir = pd.concat([edges[["u","v"]], edges[["u","v"]].rename(columns={"u":"v","v":"u"})]).drop_duplicates()

neighbors_all = defaultdict(set)
for u, v in edges_undir.itertuples(index=False):
    neighbors_all[u].add(v)

len(neighbors_all), edges_undir.shape

"""## Compute median edge length by route_type → derive mode-specific hop depths
**This solves your “max hops” concern. We convert a target network distance into mode-specific hops automatically.**
"""

# attach route_type to edges using trip_id -> route_id -> route_type
edges_rt = edges.merge(trips[["trip_id","route_id"]], on="trip_id", how="left").merge(routes[["route_id","route_type"]], on="route_id", how="left")

# attach coords to endpoints
coord = stops2[["stop_id","stop_lat","stop_lon"]].drop_duplicates()
edges_rt = edges_rt.merge(coord, left_on="u", right_on="stop_id", how="left").rename(columns={"stop_lat":"lat_u","stop_lon":"lon_u"}).drop(columns=["stop_id"])
edges_rt = edges_rt.merge(coord, left_on="v", right_on="stop_id", how="left").rename(columns={"stop_lat":"lat_v","stop_lon":"lon_v"}).drop(columns=["stop_id"])

edges_rt = edges_rt.dropna(subset=["lat_u","lon_u","lat_v","lon_v","route_type"]).copy()
edges_rt["route_type"] = pd.to_numeric(edges_rt["route_type"], errors="coerce").astype("Int64")
edges_rt["edge_m"] = haversine_m(edges_rt["lat_u"], edges_rt["lon_u"], edges_rt["lat_v"], edges_rt["lon_v"])

edge_stats = edges_rt.groupby("route_type")["edge_m"].median().reset_index().sort_values("edge_m")
edge_stats

route_type_name = {0:"streetcar", 1:"subway", 3:"bus"}

edge_median = {route_type_name.get(int(rt), str(rt)): float(med)
               for rt, med in zip(edge_stats["route_type"].dropna(), edge_stats["edge_m"])}

hops_by_mode = {}
for mode, med in edge_median.items():
    if med > 0:
        hops_by_mode[mode] = int(np.ceil(TARGET_DIST_M / med))

hops_by_mode

"""# PART 6 — Choose an anchor hub per event (single consistent anchor)

## MULTI-ANCHORS PER EVENT (nearest stop per mode within VENUE_RADIUS_M)
**Output: events["anchor_stops"] as a list of stop_ids**
"""

stop_lat = stops2["stop_lat"].to_numpy()
stop_lon = stops2["stop_lon"].to_numpy()
stop_id  = stops2["stop_id"].astype(str).to_numpy()
stop_mode_arr = stops2["mode"].astype(str).to_numpy()

ANCHOR_MODES = ["subway", "streetcar", "bus"]  # choose which modes you want

anchor_lists = []
anchor_summary = []

# Build arrays we can index fast
stop_route_types = stops2["route_types"].tolist()  # list-of-lists aligned to stops2 row order

MODE_TO_RT = {"streetcar": 0, "subway": 1, "bus": 3}

for _, e in events.iterrows():
    d = haversine_m(e["venue_lat"], e["venue_lon"], stop_lat, stop_lon)

    # all stops within venue radius
    within = np.where(d <= VENUE_RADIUS_M)[0]
    anchors = []

    for m in ANCHOR_MODES:
        rt = MODE_TO_RT[m]

        # select stops within radius that SERVE this route_type
        idx_m = [i for i in within
                 if isinstance(stop_route_types[i], list) and (rt in stop_route_types[i])]

        if len(idx_m) == 0:
            continue

        idx_m = np.array(idx_m, dtype=int)
        j = idx_m[np.argmin(d[idx_m])]
        anchors.append(stop_id[j])

    # if nothing found, fallback to nearest stop overall
    if len(anchors) == 0:
        anchors.append(stop_id[int(np.argmin(d))])

    # remove duplicates
    anchors = sorted(set(anchors))
    anchor_lists.append(anchors)
    anchor_summary.append(",".join(anchors))

events = events.copy()
events["anchor_stops"] = anchor_lists
events["anchor_stops_str"] = anchor_summary  # for debugging / printing

events[["venue","event_name","start_dt","anchor_stops_str"]].head(10)

events.venue.unique()

"""# PART 7 — Load + clean crime, build crime_assigned to hubs

## Load crime + build OCC_DT_LOCAL (timestamp)
**Provides correct coordinates and a consistent hourly timestamp.**
"""

crime = crime_raw.copy()
crime.columns = [c.strip().upper() for c in crime.columns]

# --- lat/lon detection ---
lat_candidates = [c for c in crime.columns if c in ["LAT_WGS84"]]
lon_candidates = [c for c in crime.columns if c in ["LONG_WGS84"]]
assert lat_candidates and lon_candidates, "Couldn't detect crime lat/lon columns."

LAT_COL, LON_COL = lat_candidates[0], lon_candidates[0]
crime["LAT"] = pd.to_numeric(crime[LAT_COL], errors="coerce")
crime["LON"] = pd.to_numeric(crime[LON_COL], errors="coerce")

# --- datetime detection ---
if "OCC_DT_LOCAL" in crime.columns:
    crime["OCC_DT_LOCAL"] = pd.to_datetime(crime["OCC_DT_LOCAL"], errors="coerce")
else:
    assert "OCC_DATE" in crime.columns, "Need OCC_DATE or OCC_DT_LOCAL in crime data."
    crime["OCC_DATE"] = pd.to_datetime(crime["OCC_DATE"], errors="coerce")
    hour_candidates = [c for c in crime.columns if c in ["OCC_HOUR","HOUR","OCCURRENCE_HOUR","OCC_HR"]]
    if hour_candidates:
        HCOL = hour_candidates[0]
        crime["OCC_HOUR"] = pd.to_numeric(crime[HCOL], errors="coerce")
    else:
        crime["OCC_HOUR"] = crime["OCC_DATE"].dt.hour
    crime["OCC_DT_LOCAL"] = crime["OCC_DATE"] + pd.to_timedelta(crime["OCC_HOUR"].fillna(0).astype(int), unit="h")

crime = crime.dropna(subset=["OCC_DT_LOCAL","LAT","LON"]).copy()
crime[["OCC_DT_LOCAL","LAT","LON"]].head()

"""## Assign each crime to nearest TTC hub (station_id), within CRIME_TO_STOP_MAX_M
**Converts point crimes into hub-level events so you can analyze “crime near transit hubs”.**
"""

# ===== REPLACE CELL 34 =====
# Assign each crime to nearest TTC STOP (stop_id), within CRIME_TO_STOP_MAX_M

stop_lat = stops2["stop_lat"].to_numpy()
stop_lon = stops2["stop_lon"].to_numpy()
stop_id  = stops2["stop_id"].astype(str).to_numpy()

crime_lat = crime["LAT"].to_numpy()
crime_lon = crime["LON"].to_numpy()

assigned_stop = []
assigned_dist = []

deg_thresh = CRIME_TO_STOP_MAX_M / 111000.0 * 2.5

for i in range(len(crime)):
    lat = crime_lat[i]
    lon = crime_lon[i]

    mask = (np.abs(stop_lat - lat) <= deg_thresh) & (np.abs(stop_lon - lon) <= deg_thresh)
    if not np.any(mask):
        assigned_stop.append(None)
        assigned_dist.append(np.nan)
        continue

    d = haversine_m(lat, lon, stop_lat[mask], stop_lon[mask])
    j = int(np.argmin(d))
    best = float(d[j])

    if best <= CRIME_TO_STOP_MAX_M:
        idx = np.where(mask)[0][j]
        assigned_stop.append(stop_id[idx])
        assigned_dist.append(best)
    else:
        assigned_stop.append(None)
        assigned_dist.append(best)

crime_assigned = crime.copy()
crime_assigned["stop_id"] = assigned_stop
crime_assigned["crime_to_stop_m"] = assigned_dist

crime_assigned = crime_assigned.dropna(subset=["stop_id"]).copy()
crime_assigned["stop_id"] = crime_assigned["stop_id"].astype(str)

crime_assigned.shape, crime_assigned["crime_to_stop_m"].describe()

"""# PART 8 — Build hub-hour crime panel (outcome variable for DiD)

## Aggregate crimes to hub-hour frequency panel
**This is dependent variable for DiD: “crimes per hub per hour”.**
"""

# ===== REPLACE CELL 37 =====
# Build stop-hour crime panel: (stop_id, hour) -> crime_count

crime_assigned["hour"] = crime_assigned["OCC_DT_LOCAL"].dt.floor(PANEL_FREQ)

panel = (
    crime_assigned.groupby(["stop_id", "hour"])
    .size()
    .rename("crime_count")
    .reset_index()
)

panel["hour_of_week"] = (panel["hour"].dt.dayofweek * 24 + panel["hour"].dt.hour).astype(int)
panel["year_month"] = panel["hour"].dt.strftime("%Y-%m")

panel.head(), panel.shape

"""# PART 9 — Build MULTI-SOURCE BFS ON STOP GRAPH"""

def multi_source_bfs(anchors: list[str], max_hops: int | None = None) -> dict:
    """
    Returns dict: stop_id -> min hop distance to ANY anchor in anchors.
    """
    dist = {}
    q = deque()

    # initialize all anchors at hop 0
    for a in anchors:
        a = str(a)
        dist[a] = 0
        q.append(a)

    while q:
        cur = q.popleft()
        d = dist[cur]
        if max_hops is not None and d >= max_hops:
            continue

        for nb in neighbors_all.get(cur, []):
            if nb not in dist:
                dist[nb] = d + 1
                q.append(nb)

    return dist

"""# PART 10 — Build event exposure sets (treated/control by hop, mode-aware)

## Decide hop threshold per event based on anchor mode
**We infer anchor mode from hubs.mode. Then choose hop depth from hops_by_mode.**
**solves your concern that “bus hops ≠ subway hops” in physical distance.**
"""

# ===== REPLACE CELL 42 =====
# Use hops_by_mode to create event-specific treated/control hop thresholds (Option 1)

stopid_to_route_types = stops2.set_index("stop_id")["route_types"].to_dict()

RT_TO_MODE = {0: "streetcar", 1: "subway", 3: "bus"}

def event_anchor_modes(anchor_stops):
    modes = set()
    for s in anchor_stops:
        rts = stopid_to_route_types.get(str(s), [])
        if isinstance(rts, list):
            for rt in rts:
                if rt in RT_TO_MODE:
                    modes.add(RT_TO_MODE[rt])
    # fallback if we failed to detect anything
    if len(modes) == 0:
        modes.add("bus")
    return sorted(modes)

def choose_event_hops(anchor_stops):
    modes = event_anchor_modes(anchor_stops)
    # Convert TARGET_DIST_M into hops per mode; fallback if missing
    mode_hops = [hops_by_mode.get(m, None) for m in modes]
    mode_hops = [h for h in mode_hops if h is not None]
    if len(mode_hops) == 0:
        # reasonable fallback
        treated = 6
    else:
        # safest: cover the largest hop-needed mode so treated region reaches ~TARGET_DIST_M
        treated = int(max(mode_hops))

    # define a control ring relative to treated (keeps logic consistent across events)
    control_min = treated + 4
    control_max = treated + 12

    return treated, control_min, control_max, modes

tmp = events["anchor_stops"].apply(choose_event_hops)
events["treated_hops"] = tmp.apply(lambda x: x[0])
events["control_hops_min"] = tmp.apply(lambda x: x[1])
events["control_hops_max"] = tmp.apply(lambda x: x[2])
events["anchor_modes"] = tmp.apply(lambda x: x[3])

events[["venue","event_name","anchor_stops_str","anchor_modes","treated_hops","control_hops_min","control_hops_max"]].head(10)

events[["venue","event_name","anchor_stops_str","anchor_modes","treated_hops","control_hops_min","control_hops_max"]].tail(10)

"""## Build EVENT EXPOSURE USING MIN-HOPS TO MULTI-ANCHORS
**Nodes are stop_id now**
"""

# ===== REPLACE CELL 44 =====
# EVENT EXPOSURE using multi-anchors + per-event mode-aware hop thresholds

events = events.reset_index(drop=True).copy()
events["event_id"] = events.index.astype(int)

exposure_rows = []

for _, e in events.iterrows():
    event_id = int(e["event_id"])
    anchors = e["anchor_stops"]

    treated_hops = int(e["treated_hops"])
    cmin = int(e["control_hops_min"])
    cmax = int(e["control_hops_max"])

    # BFS only needs to expand out to cmax
    dmap = multi_source_bfs(anchors, max_hops=cmax)

    sub = pd.DataFrame({"stop_id": list(dmap.keys()), "hop": list(dmap.values())})
    sub["stop_id"] = sub["stop_id"].astype(str)

    sub["treated_stop"] = (sub["hop"] <= treated_hops).astype(int)
    sub["control_stop"] = ((sub["hop"] >= cmin) & (sub["hop"] <= cmax)).astype(int)

    sub = sub[(sub["treated_stop"] == 1) | (sub["control_stop"] == 1)].copy()

    sub["event_id"] = event_id
    sub["start_dt"] = e["start_dt"]
    sub["venue"] = e["venue"]
    sub["event_category"] = e["event_category"]
    sub["event_name"] = e["event_name"]
    sub["anchor_stops_str"] = e["anchor_stops_str"]
    sub["anchor_modes"] = ",".join(e["anchor_modes"])
    sub["treated_hops"] = treated_hops
    sub["control_hops_min"] = cmin
    sub["control_hops_max"] = cmax

    exposure_rows.append(sub)

event_exposure = pd.concat(exposure_rows, ignore_index=True)
event_exposure.head(), event_exposure.shape

"""# PART 11 — Build stacked DiD dataset and run regressions

## Build stacked event-window dataset (event × stop × hour)
**panel must be stop-hour: (stop_id, hour) -> crime_count**
"""

panel_key = panel.set_index(["stop_id","hour"])

did_rows = []
for event_id, g in event_exposure.groupby("event_id", sort=False):
    start_dt = g["start_dt"].iloc[0]

    window_start = (start_dt - pd.Timedelta(hours=PRE_HOURS)).floor(PANEL_FREQ)
    window_end   = (start_dt + pd.Timedelta(hours=POST_HOURS)).ceil(PANEL_FREQ)
    hours = pd.date_range(window_start, window_end, freq=PANEL_FREQ, inclusive="left")

    tmp = (
        g[["event_id","stop_id","hop","treated_stop","control_stop","start_dt","venue","event_category","event_name","anchor_stops_str"]]
        .drop_duplicates()
        .assign(key=1)
        .merge(pd.DataFrame({"hour": hours, "key": 1}), on="key", how="outer")
        .drop(columns=["key"])
    )

    tmp["rel_hours"] = (tmp["hour"] - start_dt).dt.total_seconds() / 3600.0
    tmp["post"] = (tmp["rel_hours"] >= 0).astype(int)

    tmp["hour_of_week"] = (tmp["hour"].dt.dayofweek * 24 + tmp["hour"].dt.hour).astype(int)
    tmp["year_month"] = tmp["hour"].dt.strftime("%Y-%m")

    idx = list(zip(tmp["stop_id"], tmp["hour"]))
    tmp["crime_count"] = panel_key.reindex(idx)["crime_count"].values
    tmp["crime_count"] = tmp["crime_count"].fillna(0).astype(int)

    tmp["y"] = np.log1p(tmp["crime_count"])
    did_rows.append(tmp)

did = pd.concat(did_rows, ignore_index=True)
did.head(), did.shape

"""## Hop-bin DiD regression (propagation pattern)
**This estimates “post uplift” at hop=0,1,2,… relative to control ring → the propagation curve.**
"""

did2 = did[(did["treated_stop"]==1) | (did["control_stop"]==1)].copy()

did2 = did2.merge(
    events[["event_id","treated_hops","control_hops_min","control_hops_max"]],
    on="event_id",
    how="left"
)

did2["norm_hop"] = did2["hop"] / did2["treated_hops"].clip(lower=1)

def norm_bin(r):
    if r < 0.25: return "near_0_25"
    if r < 0.50: return "near_25_50"
    if r < 1.00: return "near_50_100"
    return "control_ring" if (r >= did2["control_hops_min"].min()/did2["treated_hops"].max()) else "beyond_treated"

# simpler: force control_stop as control_ring
did2["bin"] = np.where(did2["control_stop"]==1, "control_ring",
                       pd.cut(did2["norm_hop"], bins=[-1,0.25,0.5,1.0,1e9],
                              labels=["near_0_25","near_25_50","near_50_100","beyond_treated"]).astype(str))

agg = (did2
       .groupby(["event_id","hour","post","hour_of_week","year_month","bin"], as_index=False)
       .agg(crime_count=("crime_count","sum"), n_stops=("stop_id","nunique")))

agg["crime_rate"] = agg["crime_count"] / agg["n_stops"].clip(lower=1)
agg["y"] = np.log1p(agg["crime_rate"])
agg.shape

agg

if "event_start_dt" not in agg.columns:
    if "did" in globals() and {"event_id", "start_dt"}.issubset(did.columns):
        event_start = (
            did[["event_id", "start_dt"]]
            .drop_duplicates()
            .rename(columns={"start_dt": "event_start_dt"})
        )
    elif "events" in globals() and ("start_dt" in events.columns):
        # If events already has event_id column use it; else assume index-based event_id
        if "event_id" in events.columns:
            event_start = events[["event_id", "start_dt"]].drop_duplicates().rename(columns={"start_dt":"event_start_dt"})
        else:
            event_start = events[["start_dt"]].reset_index(drop=True).copy()
            event_start["event_id"] = event_start.index.astype(int)
            event_start = event_start.rename(columns={"start_dt":"event_start_dt"})
    else:
        raise ValueError("Need event start times: provide did[['event_id','start_dt']] or events with start_dt.")
    agg = agg.merge(event_start, on="event_id", how="left")

# Basic checks
if agg["event_start_dt"].isna().any():
    missing = agg.loc[agg["event_start_dt"].isna(), "event_id"].nunique()
    raise ValueError(f"event_start_dt missing for {missing} event_id(s). Fix event_id alignment before proceeding.")

# ---------- 1) Build per-row rate and relative hour ----------
df = agg.copy()
df["hour"] = pd.to_datetime(df["hour"])
df["event_start_dt"] = pd.to_datetime(df["event_start_dt"])

df["rate"] = df["crime_count"] / df["n_stops"].clip(lower=1)
df["rel_hour"] = (df["hour"] - df["event_start_dt"]).dt.total_seconds() / 3600.0

# Optional: round rel_hour to align to your panel freq (e.g., 1H)
# If your panel is hourly, this makes plotting cleaner.
df["rel_hour"] = df["rel_hour"].round(0).astype(int)

# ---------- 2) Choose plotting window ----------
PRE_H = 6
POST_H = 10
df = df[(df["rel_hour"] >= -PRE_H) & (df["rel_hour"] <= POST_H)].copy()

# Keep only bins you care about and ensure control exists
bins_keep = ["control_ring", "near_0_25", "near_25_50", "near_50_100"]
df = df[df["bin"].isin(bins_keep)].copy()

# ---------- 3) Compute the difference curves (mean treated - mean control) ----------
# First average across events at each (rel_hour, bin)
mean_by_t = (
    df.groupby(["rel_hour", "bin"], as_index=False)["rate"]
      .mean()
      .pivot(index="rel_hour", columns="bin", values="rate")
      .sort_index()
)

if "control_ring" not in mean_by_t.columns:
    raise ValueError("control_ring not present after filtering. Check your bin construction.")

diff_curves = mean_by_t.copy()
for b in diff_curves.columns:
    if b != "control_ring":
        diff_curves[b] = diff_curves[b] - diff_curves["control_ring"]

# Keep only treated bins for plotting
treated_bins = [b for b in bins_keep if b != "control_ring"]
diff_curves_plot = diff_curves[treated_bins].copy()

# ---------- 4) Bootstrap confidence intervals by resampling events ----------
def bootstrap_diff_curves(df_in: pd.DataFrame, bins: list, B: int = 300, seed: int = 42):
    rng = np.random.default_rng(seed)
    event_ids = df_in["event_id"].unique()
    rel_hours = np.sort(df_in["rel_hour"].unique())

    boot_store = {b: [] for b in bins}

    # Pre-slice by event to make bootstrapping faster
    by_event = {eid: g for eid, g in df_in.groupby("event_id")}

    for _ in range(B):
        sample_eids = rng.choice(event_ids, size=len(event_ids), replace=True)
        # concatenate sampled events (fast-ish)
        tmp = pd.concat([by_event[eid] for eid in sample_eids], ignore_index=True)

        m = (
            tmp.groupby(["rel_hour", "bin"], as_index=False)["rate"]
               .mean()
               .pivot(index="rel_hour", columns="bin", values="rate")
               .reindex(rel_hours)
        )

        # If some bins missing at some rel_hours, fill with 0 (conservative with sparse data)
        m = m.fillna(0.0)

        for b in bins:
            boot_store[b].append((m[b] - m["control_ring"]).to_numpy())

    # Convert to arrays: shape (B, T)
    out = {}
    for b in bins:
        arr = np.vstack(boot_store[b])
        out[b] = {
            "rel_hour": rel_hours,
            "mean": arr.mean(axis=0),
            "lo": np.quantile(arr, 0.025, axis=0),
            "hi": np.quantile(arr, 0.975, axis=0),
        }
    return out

boot = bootstrap_diff_curves(df, treated_bins, B=300, seed=42)

# ---------- 5) Plot ----------
plt.figure(figsize=(10, 5))
for b in treated_bins:
    x = boot[b]["rel_hour"]
    y = boot[b]["mean"]
    lo = boot[b]["lo"]
    hi = boot[b]["hi"]
    plt.plot(x, y, label=b)
    plt.fill_between(x, lo, hi, alpha=0.2)

plt.axvline(0, linestyle="--")
plt.axhline(0, linestyle=":")
plt.xlabel("Relative hour (event start = 0)")
plt.ylabel("Excess crime rate vs control_ring (per stop)")
plt.title("Event-study difference curves (treated bins minus control ring)")
plt.legend()
plt.tight_layout()
plt.show()

# ---------- 6) Optional: quick numeric summary around the spike window ----------
# Average excess effect in [0,2] hours after event start (can change)
summary_window = (0, 2)
summ_rows = []
for b in treated_bins:
    x = boot[b]["rel_hour"]
    mask = (x >= summary_window[0]) & (x <= summary_window[1])
    summ_rows.append({
        "bin": b,
        "avg_excess_rate_0_2h": float(np.mean(boot[b]["mean"][mask])),
        "ci_lo": float(np.mean(boot[b]["lo"][mask])),
        "ci_hi": float(np.mean(boot[b]["hi"][mask])),
    })

summary_df = pd.DataFrame(summ_rows).sort_values("bin")
print(summary_df)























